# Generated by Django 5.0.1 on 2024-02-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('frontPage', models.ImageField(upload_to='')),
                ('page1', models.ImageField(upload_to='')),
                ('page2', models.ImageField(upload_to='')),
                ('page3', models.ImageField(upload_to='')),
                ('page4', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
